version: '3.9'
services:
  vlm-api-staging:
    # Other configuration
    container_name: vlm-api-staging
    build:
      context: ./
      dockerfile: Dockerfile.staging
    env_file: ./.env
    ports:
      - "3100:3100"
    restart: on-failure
    healthcheck:
      test: curl --fail -s http://localhost:3000/_health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"