
version: '3.9'
services:
  vlm-api-preprod:
    # Other configuration
    container_name: vlm-api-preprod
    build:
      context: ./
      dockerfile: Dockerfile.preprod
    env_file: ./.env
    ports:
      - "3100:3100"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
